### ISSUE TITLE
Counter data averaging

### ISSUE THREAD

**Issue by Makingnoise** [samuelkim314/Diamond_NV_Experiment#1]
Hi. Thank you so much for sharing your LabVIEW code for the NV setup. I am working on the exact same thing and want to ask a question about the counter. Did you use a NI multifunctional PCI board for counting data from an avalanche photodiode? 

If so, did you do data averaging? For a given data acquisition window, the photodiode may give out different numbers of pulses with a variance.

**Comment by samuelkim314** [comment]
Hello, unfortunately since I have not touched this project for many years, I don't remember any of the details and can't answer your questions.

**Comment by Makingnoise** [comment]
Thank you for your reply.
